title: Oak Notes
description: This is site for Oak's note. It's random note, so you'll see several topic in view languages on this site. Because I'm gonna use both of Bahasa and English.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
